### ISSUE TITLE
Extension No Longer Working

### ISSUE THREAD

**Issue by Yaanu** [WilliamWelsh/Letterboxd-Rotten-Tomatoes-Addon#1]
It appears that the Addon is not working due to the following error:

>VM7609:1 Uncaught SyntaxError: Unexpected end of JSON input
>at JSON.parse (<anonymous>)
>at content.js:78`

Here are lines 76-78:
>RTJSON = RTJSON.substring(RTJSON.indexOf('window.mpscall = ') + 17);
>RTJSON = RTJSON.substring(0, RTJSON.indexOf(';'));
>RTJSON = JSON.parse(RTJSON);`

**Comment by WilliamWelsh** [comment]
Thanks for letting me know. It's having trouble parsing because there is no data, for some reason calling to Rotten Tomatoes from Letterboxd just returns empty data. It can call to Omdb just fine (where it gets half the data), but I'm unable to figure out why this is happening. I tried using different methods to fetch website data, but Rotten Tomatoes just isn't having it. I'm going to leave this issue open.

**Comment by luanmarcel** [comment]
Yet is not working?

(sorry, bad english...)

**Comment by WilliamWelsh** [comment]
> 
> Yet is not working?
> 

Correct, Chrome has modified their rules so you can't get data from another site other than the one you're on, therefore there's no way for this extension to work anymore to my knowledge.

**Comment by 1netanel** [comment]
have you tried rotten tomatos API ? 
(https://developer.fandango.com/rotten_tomatoes)

**Comment by Gabriel-p** [comment]
> Correct, Chrome has modified their rules so you can't get data from another site other than the one you're on, therefore there's no way for this extension to work anymore to my knowledge.

Oh that's a shame
